[package]
name = "voxelized-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
js-sys = "0.3"
once_cell = "1"
web-sys = { version = "0.3", features = [
    "Window","Document","HtmlCanvasElement","HtmlImageElement","CanvasRenderingContext2d","ImageData",
    "WebGl2RenderingContext","WebGlProgram","WebGlBuffer","WebGlTexture","WebGlUniformLocation",
    "Performance"
] }
